### ISSUE TITLE
Constant error with updating from 0.1.0

### ISSUE THREAD

**Issue by apoapostolov** [andriusch/foundry-item-to-chat#1]
![image](https://user-images.githubusercontent.com/4083812/150571522-a74837f6-7ee2-4717-92f3-615614bac7d6.png)

**Comment by elemorelli** [comment]
I'm having the same error when running an update for all modules, also with Item to Chat 0.1.0

Otherwise, the module is working fine! 😄

**Comment by andriusch** [comment]
Sorry for late reply, but for anyone having this issue please uninstall and reinstall the module. 0.1.0 had a problem with manifest which was fixed in 0.1.1
