### ISSUE TITLE
BUG: This is somehow still not core in v10.

### ISSUE THREAD

**Issue by esheyw** [andriusch/foundry-item-to-chat#3]
therefore feature request: please update this mod for compatibility. 😅Currently it's throwing an error every time its used, at least in pf2e.

**Comment by andriusch** [comment]
Hi, thanks for your report. I've tested it for v10 and it seems to work fine (aside from not being marked as compatible). Is there a specific issue you've encountered? Could you provide exact steps to reproduce? E.g. did you have a token selected, what exact item you used?

**Comment by esheyw** [comment]
So I would swear on my life it was erroring the night I made the report, but I can't recreate it, even with my full stable of modules active.  I guess my only request is to bump your verified field in your manifest so my yellow boxes can go away 😀 Sorry, and thanks.
