### ISSUE TITLE
Could you please create a non PF version tto, that would work with coustom system builder?

### ISSUE THREAD

**Issue by Jonny134** [andriusch/foundry-item-to-chat#4]
could you please create a non PF version tto, that would work with coustom system builder?

**Comment by andriusch** [comment]
I'm sorry, but the functions I'm using are PF2e specific, while nothing is stopping any other system from implementing the same functions, I'm not aware if any are. I would probably accept any pull request that implements integration with another system, as long as it doesn't rely on internals of said system, but I'm not going to actively look into integrating this with other systems.
